version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "3000:3000"
    environment:
      - .env
    restart: unless-stopped
